<meta charset="UTF-8">
<meta name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">

<meta name="author" content="Josip Igrec">
<meta name="theme-color" content="#1E1E1E">
<meta name="application-name" content="AuResS Viewer - View AuResS room data"/>
<meta name="msapplication-TileColor" content="#1E1E1E">
<meta name="theme-color" content="#232323">
